server:
  port: 8888
  servlet:
    context-path: /api

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/first?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root
    url: jdbc:mysql://10.240.46.236:3306/dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: x4iCy1uv
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss"
    # Locale used for formatting
    time-zone: "GMT+8"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

