spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

bos:
  stsEndpoint : http://sts.endpoint.com
  accessKeyId : 123
  accessKeySecret : 456
  endpoint : https://endpoint.com
  bucketName : bucketName
  envPath: dev