server:
  port: 8881
  servlet:
    context-path: /api

spring:
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss"
    # Locale used for formatting
    time-zone: "GMT+8"

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

bos:
  stsEndpoint : http://sts.endpoint.com
  accessKeyId : 123
  accessKeySecret : 456
  endpoint : https://endpoint.com
  bucketName : bucketName
  envPath: dev